### ISSUE TITLE
Troubleshooting cloning errors

### ISSUE THREAD

**Issue by khusrav13** [doomL/langchain-langgraph-tutorial#1]
Hello, there’s a small issue with cloning the Git repository.

Tutorial 1: Introduction to LangChain

git clone https://github.com/your-repo/langchain-tutorials.git
cd langchain-tutorials/tutorial-1

[](https://github.com/doomL/langchain-langgraph-tutorial/tree/main/Tutorial01)

```
git clone https://github.com/your-repo/langchain-tutorials.git
Cloning into 'langchain-tutorials'...
remote: Repository not found.
fatal: repository 'https://github.com/your-repo/langchain-tutorials.git/' not found
```

**Comment by doomL** [comment]
Hi, thank for the issue.
I'll fix all the readme and make you a fixed commit

**Comment by khusrav13** [comment]
Thank you!!!

**Comment by doomL** [comment]
Hi, the repo has been fixed.
If you have other problems feel free to contact me.

**Comment by khusrav13** [comment]
Thank you so much
